services:
  postgre:
    image: postgres:13.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Realmadrid@07
      POSTGRES_USER: brunosilvar
      POSTGRES_DB: kubenews
  kubenews:
    image: brunosilvar/kube-news:v1
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: ./dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: brunosilvar
      DB_PASSWORD: Realmadrid@07
      DB_HOST: postgre

networks: 
  kubenews_net:
    driver: bridge
  

